services:

  postgres:
    image: postgres:16.8-alpine3.20
    container_name: zapbackend-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zapbackend
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - zapbackend-db:/var/lib/postgresql/data
    networks:
      - zapbackend-network

#  pgadmin4:
#    image: dpage/pgadmin4:9.0.0
#    container_name: zapbackend-pgadmin4
#    environment:
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    ports:
#      - "15432:80"
#    networks:
#      - zapbackend-network

  rabbitmq1:
    image: rabbitmq:4.0.7-management-alpine
    container_name: rabbitmq1
    restart: always
    hostname: rabbitmq1
    networks:
      - "zapbackend-network"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: UTC

volumes:
  zapbackend-db:
    driver: local

networks:
  zapbackend-network:
    driver: bridge
