spring:
  application:
    name: ZapBackend
  config:
    import: optional:classpath:.env[.properties]
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?TimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: off
  jackson:
    time-zone: UTC
zap-backend:
  jwt:
    expiration-seconds: 3500
logging:
  level:
    org.springframework.security: debug
