spring:
logging:
  level:
    org.springframework.security: error
    br.com.gabxdev: error
server:
  port: 443
  ssl:
    key-store: file:/app/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: springboot
    enabled: true