spring:
  application:
    name: ZapBackend
  config:
    import: optional:classpath:.env[.properties]
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?TimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: off
  jackson:
    time-zone: UTC
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
zap-backend:
  jwt:
    expiration-seconds: 3600
    secret-key: ${SECRET_KEY}
logging:
  level:
    org.springframework.security: debug
    br.com.gabxdev: debug
