spring:
  application:
    name: ZapBackend
  config:
    import: optional:classpath:.env[.properties]
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?TimeZone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: off
  jackson:
    time-zone: UTC
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false
zap-backend:
  jwt:
    expiration-seconds: 36000
    secret-key: ${SECRET_KEY}
  stomp-broker-relay:
    relay-host: ${RELAY_HOST}
    relay-port: ${RELAY_PORT}
    client-login: ${CLIENT_LOGIN}
    client-passcode: ${CLIENT_PASSCODE}
    system-login: ${SYSTEM_LOGIN}
    system-passcode: ${SYSTEM_PASSCODE}
logging:
  level:
    org.springframework.security: debug
    br.com.gabxdev: debug
